default: &default
  adapter: postgresql
  encoding: unicode
development:
  <<: *default
  database: sitemap_blog
  username: root
  password: root
  # s3_bucket: <%= ENV["S3_BUCKET"] %>
  # s3_key: <%= ENV["S3_KEY"] %>
  # s3_secret: <%= ENV["S3_SECRET"] %>
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] %>
  # sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>

production:
  <<: *default
  database: sitemap_blog
  username: root
  password: root 